config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'movies#index'
  resources :movies do
    collection do
      get 'rank', to: 'movies#rank'
    end
    resources :reviews
  end
  resources :users do
    collection do
      get 'follow', to: 'users#follow'
      get 'follower', to: 'users#follower'
    end
  end
  get 'tags/:tag', to: 'movies#index', as: :tag

  get 'movies/search', to: 'movies#search'
  post 'movies/search', to: 'movies#search'

  resources :relationships, only: [:create, :destroy]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search, :rank]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :admin?, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    if params[:tag]
      movies = Movie.tagged_with(params[:tag]).order("created_at DESC")
      @movies = movies.page(params[:page]).per(8)
    else
      movies = Movie.includes(:user).order("created_at DESC")
      @movies = movies.page(params[:page]).per(8)
    end
    @new_movie = Movie.new
  end

  def rank
    # @story_ranks = Movie.find(Review.group(:review_story).order('avg(review_story) desc').pluck(:movie_id))
    @movies = Movie.includes(:user)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    reviews = Review.where(movie_id: @movie.id).order("created_at DESC")
    @reviews = reviews.page(params[:page]).per(4)
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to movie_path(@movie.id)
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    redirect_to root_path
  end

  def search
    @movies = Movie.includes(:user).order("created_at DESC")
    @movies = @movies.tagged_with(movie_params[:tag_list], any: true).order("created_at DESC") | Movie.where('movie_title LIKE ?', "%#{movie_params[:tag_list]}%").order("created_at DESC")
  end

  private
  def movie_params
    params.require(:movie).permit(:movie_title, :movie_text, :long, :release_date, :producer, :character, :movie_image, :tag_list).merge(user_id: current_user.id)
  end

  def search_params
    params.require(:movie).permit(:movie_title, :tag_list)
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end
  
  def admin?
    unless current_user.admin?
      redirect_to root_path
    end
  end

end

app/views/movies/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('sympasee_logo.png' , size: '200x50'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">商品の情報を入力</h2>
    <%= form_with model: @movie, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 出品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        作品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :movie_image, id:"item-image" %>
      </div>
    </div>
    <%# /出品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
          作品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :movie_title, class:"movies-text", id:"movie-title", placeholder:"商品名（必須 50文字まで)", maxlength:"50" %>
      <div class="movie-form">
        <div class="weight-bold-text">
          作品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :movie_text, class:"movies-text", id:"movie-text", placeholder:"作品の説明（必須 500文字まで）", rows:"7" ,maxlength:"500" %>
      </div>
      <div class="movie-form">
        <div class="weight-bold-text">
          動画の長さ
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :long, class:"movies-short-text", id:"movie-long", placeholder:"（例）120分、全13話", maxlength:"15" %>
      </div>
      <div class="movie-form">
        <div class="weight-bold-text">
          制作者
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :producer, class:"movies-text", id:"movie-producer", placeholder:"制作者（必須 50文字まで）", rows:"1" ,maxlength:"50" %>
      </div>
      <div class="movie-form">
        <div class="weight-bold-text">
          演者
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :character, class:"movies-text", id:"movie-character", placeholder:"制作者（必須 200文字まで）", rows:"2" ,maxlength:"200" %>
      </div>
      <div class="movie-form">
        <div class="weight-bold-text">
          作品の公開日
          <span class="indispensable">必須</span>
        </div>
        <div class='input-release-wrap'>
          <%= raw sprintf(
                      f.date_select(
                        :release_date,
                        class:'select-release',
                        id:"release-date",
                        use_month_numbers: true,
                        prompt:'--',
                        start_year: 1930,
                        end_year: (Time.now.year + 5),
                        date_separator: '%s'),
                      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
        </div>
      </div>
    <%# /商品名と商品説明 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "作品の内容を更新する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= render "shared/footer" %>

app/views/movies/index.html.erb
<%= render "shared/header" %>
<div class='movie-main'>
  <%# ピックアップタイトルの部分 %>
  <div class="container pickup_title">
    <h2 class="title">PICKUPタイトル</h2>
  </div>

  <div id="carousel-2" class="carousel slide" data-interval="5000">
    <ol class="carousel-indicators">
      <li data-target="#carousel-2" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-2" data-slide-to="1"></li>
      <li data-target="#carousel-2" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner text-center">
        <div class="carousel-item active">
          <%= link_to image_tag("pickup1.jpeg", size: '900x500', alt: 'First slide'), movie_path(1) %>
        </div>
        <div class="carousel-item">
          <%= link_to image_tag("pickup2.jpeg", size: '900x500', alt: 'Second slide'), movie_path(2) %>
        </div>
        <div class="carousel-item">
          <%= link_to image_tag("pickup3.jpeg", size: '900x500', alt: 'Third slide'), movie_path(3) %>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carousel-2" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-2" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <%# ピックアップタイトルの部分 %>

  <%# 作品一覧 %>
  <div class='movie-contents container-fluid'>
    <% if user_signed_in? %>
      <div class="index-search"> 
        <%= form_for(@new_movie, url: {controller: 'movies', action: 'search' }) do |f| %>
          <%= f.text_field :tag_list %>
          <%= f.submit "タイトル or タグ検索", class: "search_btn" %>
        <% end %>
      </div>
    <% end %>
    <h5 class="subtitle">新規投稿商品</h5>
    <div class="row" style="width:100%">
      <% @movies.each do |m| %>
        <div class='movie-lists, col-3'>

          <%= link_to movie_path(m.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag m.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-info'>
              <h4><%= m.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if m.tags.present? %>
              <%= raw(m.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>


        </div>
      <% end %>
    </div> 
    <%= paginate @movies %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/movies/rank.html.erb
<%= render "shared/header" %>
<div class='movie-show' style="background: url(../images/red-curtain2.jpeg); background-size: cover; background-attachment: fixed; background-position: center center; padding: 30px 0; min-height: 70vh;">
  <%# 作品一覧 %>
  <div class='movie-contents container-fluid'>

    <h5 class="story-subtitle">ストーリーランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|st| -st.avg_story }.first(3).each.with_index(1) do |st, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(st.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag st.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= st.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if st.tags.present? %>
              <%= raw(st.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

    <h5 class="story-subtitle">衝撃ランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|impact| -impact.avg_impact }.first(3).each.with_index(1) do |impact, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(impact.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag impact.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= impact.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if impact.tags.present? %>
              <%= raw(impact.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

    <h5 class="story-subtitle">感動ランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|impressed| -impressed.avg_impressed }.first(3).each.with_index(1) do |impressed, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(impressed.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag impressed.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= impressed.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if impressed.tags.present? %>
              <%= raw(impressed.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

    <h5 class="story-subtitle">楽しさランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|happy| -happy.avg_happy }.first(3).each.with_index(1) do |happy, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(happy.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag happy.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= happy.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if happy.tags.present? %>
              <%= raw(happy.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

    <h5 class="story-subtitle">登場人物ランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|character| -character.avg_character }.first(3).each.with_index(1) do |character, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(character.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag character.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= character.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if character.tags.present? %>
              <%= raw(character.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

    <h5 class="story-subtitle">映像美ランキング</h5>
    <div class="row" style="width:100%">
      <% @movies.sort_by {|beautiful| -beautiful.avg_beautiful }.first(3).each.with_index(1) do |beautiful, i| %>
        <div class='movie-lists, col-4'>
          <h4 class="ranking"><%= "#{i}位" %></h4>
          <%= link_to movie_path(beautiful.id) do %>
            <div class='movie-img-content, text-center'>
              <%= image_tag beautiful.movie_image, class: "movie-img" %>
            </div>

            <div class='movie-rank-info'>
              <h4><%= beautiful.movie_title %></h4>
            </div>
          <% end %>

          <div class='tag-list label label-primary'>
            <% if beautiful.tags.present? %>
              <%= raw(beautiful.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn text-white" }.join('&ensp;&ensp;')) %>
            <% else %>
              <p>登録しているタグはありません</p>
            <% end %>
          </div>

        </div>
      <% end %>
    </div> 

  </div>
</div>
<%= render "shared/footer" %>

app/views/movies/search.html.erb
<%= render "shared/header" %>
<div class='movie-show' style="background: url(../images/red-curtain2.jpeg); background-size: cover; background-attachment: fixed; background-position: center center; padding: 30px 0; min-height: 70vh;">

  <%# 作品一覧 %>
  <div class='movie-search-contents container-fluid'>
    <h5 class="search-subtitle">検索結果</h5>
    <div class="row" style="width:100%">
      <% if @movies.blank? %>
        <div class="no-hit-search">
          <h5>一致するタイトル・タグはありませんでした</h5>
        </div>
      <% else %>
        <% @movies.each do |m| %>
          <div class='movie-lists, col-3'>

            <%= link_to movie_path(m.id) do %>
              <div class='movie-img-content, text-center'>
                <%= image_tag m.movie_image, class: "movie-img" %>
              </div>

              <div class='movie-info'>
                <h4><%= m.movie_title %></h4>
              </div>
            <% end %>

            <div class='tag-list label label-primary'>
              <% if m.tags.present? %>
                <%= raw(m.tag_list.map { |t| link_to t, tag_path(t), class: "tag-btn" }.join('&ensp;&ensp;')) %>
              <% else %>
                <p>登録しているタグはありません</p>
              <% end %>
            </div>


          </div>
        <% end %>
      <% end %>
    </div> 
  </div>
</div>
<%= render "shared/footer" %>

app/views/movies/show.html.erb
<%= render "shared/header" %>
<div class='movie-show' style="background: url(../images/red-curtain2.jpeg); background-size: cover; background-attachment: fixed; background-position: center center; padding: 10vh 0; min-height: 70vh;">
  <%# 作品の詳細 %>
  <div class="movie-box container-fluid">
    <div class="row">
      <div class="movie-img-content col-5">
        <%= image_tag @movie.movie_image ,class:"movie-box-img" %>
      </div>
      <div class="movie-show-content col-7">
        <table>
          <tr>
            <th><%= "タイトル" %></th>
            <td><%= @movie.movie_title %></td>
          <tr>
          <tr>
            <th><%= "あらすじ" %></th>
            <td width="500" height="200">
              <div style="height:200px; width:500px; overflow-y:auto;">
                <%= @movie.movie_text %>
              </div>
            </td>
          <tr>
          <tr>
            <th><%= "監督" %></th>
            <td><%= @movie.producer %></td>
          <tr>
          <tr>
            <th><%= "役者" %></th>
            <td><%= @movie.character %></td>
          <tr>
          <tr>
            <th><%= "長さ" %></th>
            <td><%= @movie.long %></td>
          <tr>
          <tr>
            <th><%= "公開日" %></th>
            <% if @movie.release_date.blank? %>
              <td><%= "未定" %></td>
            <% else %>
              <td><%= @movie.release_date.strftime("%Y / %m / %d ") %></td>
            <% end %>
          <tr>
        </table>
      </div>
    </div>
    <div class="row">
      <div class='tag-list-show'>
        <% if @movie.tags.present? %>
          <span class="tag-title">登録タグ：</span><%= raw(@movie.tag_list.map { |t| link_to t, tag_path(t), class: "show-tag-btn text-white" }.join('&ensp;&ensp;')) %>
        <% else %>
          <p>登録しているタグはありません</p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <% if user_signed_in? && current_user.admin? %>
          <%= link_to "作品の編集", edit_movie_path(@movie.id), method: :get, class: "movie-orange-btn" %>
          <%= link_to "削除", movie_path(@movie.id), method: :delete, class:"movie-destroy" %>
      <% end %>
    </div>
    <div class="ave-review-title row">
      <%= @movie.movie_title %>のレビュー【平均値】
    </div>
    <div class="ave-review row">
      <div class="col-2"></div>
      <div class="col">
        <table align="center"  width="100%" class="review-table">
          <tr class="review-tr">
            <th class="review-th"><h4>ストーリー：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_story_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_story %>点
              </div>
            </td>
          </tr>
          <tr class="review-tr">
            <th class="review-th"><h4>衝撃：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_impact_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_impact %>点
              </div>
            </td>
          </tr>
          <tr class="review-tr">
            <th class="review-th"><h4>感動：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_impressed_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_impressed %>点
              </div>
            </td>
          </tr>
          <tr class="review-tr">
            <th class="review-th"><h4>楽しさ：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_happy_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_happy %>点
              </div>
            </td>
          </tr>
          <tr class="review-tr">
            <th class="review-th"><h4>登場人物：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_character_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_character %>点
              </div>
            </td>
          </tr>
          <tr class="review-tr">
            <th class="review-th"><h4>映像美(作画)：</h4><th>
            <td class="review-td1">
              <div class="star-rating">
                <div class="star-rating-front" style="width: <%= @movie.review_beautiful_percentage %>%">★★★★★★★★★★</div>
                <div class="star-rating-back">★★★★★★★★★★</div>
              </div>
            </td>
            <td class="review-td2">
              <div class="average-score-display">
                <%= @movie.avg_beautiful %>点
              </div>
            </td>
          </tr>
        </table>
      </div>
      <div class="col-2"></div>
    </div>
    <%# <div class="row">
      <table class="review-index-title">
        <tr class="review-index-tr">
          <th class="review-index-th"><h4>点数つけるとしたら？&ensp;&ensp;</h4></th> %>
          <%# <td class="review-index-td1"><h4>= @movie.avg_score点 / 100点（= @movie.reviews.count件のレビュー）</h4></td> %>
        <%# </tr>
      </table>
    </div> %>
    <div class="row">
      <%= link_to "レビューを書く", new_movie_review_path(@movie.id), method: :get, class: "movie-orange-btn text-white" %>
    </div>
  </div>
      <% @reviews.each do |review| %>
        <div class="index-review-content-each container-fluid">
          <% if user_signed_in? %>
            <% if (current_user.id == review.user_id) || current_user.admin? %>
              <div class="row">
                <%= link_to "削除", movie_review_path(review.movie_id, review.id), class:"review-destroy btn btn-outline-danger" %>
              </div>
            <% end %>
          <% end %>
          <table class="table is-fullwidth has-text-centered">
            <thead align="center">
              <tr>
                <th class="review-index-user">ユーザー</th>
                <th class="review-index-score">点数</th>
                <th class="review-index-text">内容</th>
                <th class="review-index-status">それぞれの評価</th>
              </tr>
            </thead>
            <tbody align="center">
              <tr>
                <td>
                  <%= link_to user_path(review.user.id) do %>
                    <%= review.user.nickname %><br>
                    <%= image_tag review.user.profile_image.variant(resize: '100x100'), class: "user-image" if review.user.profile_image.attached? %>
                    <%= image_tag "user_nil.png" , size: "100x100" unless review.user.profile_image.attached?  %>
                  <% end %>
                </td>
                <td><%= review.review_status.review_score %></td>
                <td align="left"><%= review.review_text %></td>
                <td>
                  <div class="review-index-content">
                    <table>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>ストーリー：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_story * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_story %>点</h6>
                        </td>
                      </tr>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>衝撃：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_impact * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_impact %>点</h6>
                        </td>
                      </tr>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>感動：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_impressed * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_impressed %>点</h6>
                        </td>
                      </tr>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>楽しさ：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_happy * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_happy %>点</h6>
                        </td>
                      </tr>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>登場人物：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_character * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_character %>点</h6>
                        </td>
                      </tr>
                      <tr class="review-index-content-tr">
                        <th class="review-index-content-th"><h6>映像美：</h6></th>
                        <td class="review-index-content-td1">
                          <div class="star-rating-content-index">
                            <div class="star-rating-index-front" style="width: <%= review.review_status.review_beautiful * 10 %>%">★★★★★★★★★★</div>
                            <div class="star-rating-index-back">★★★★★★★★★★</div>
                          </div>
                        </td>
                        <td class="review-index-td2">
                          <h6><%= review.review_status.review_beautiful %>点</h6>
                        </td>
                      </tr>
                    </table>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
      <%= paginate @reviews %>
</div>
<%= render "shared/footer" %>