config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'movies#index'
  resources :movies do
    collection do
      get 'rank', to: 'movies#rank'
    end
    resources :reviews
  end
  resources :users do
    collection do
      get 'follow', to: 'users#follow'
      get 'follower', to: 'users#follower'
    end
  end
  get 'tags/:tag', to: 'movies#index', as: :tag

  get 'movies/search', to: 'movies#search'
  post 'movies/search', to: 'movies#search'

  resources :relationships, only: [:create, :destroy]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follower, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    @other_user = User.find(params[:follower])
    current_user.follow(@other_user)
    # redirect_to user_path(@other_user.id)
  end

  def destroy
    @user = current_user.relationships.find(params[:id]).follower
    current_user.unfollow(params[:id])
    # redirect_to user_path(@user.id)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<%= button_to 'フォロー ', relationships_path(follower: user), class: "follow-button-follow", remote: true %>

app/views/relationships/_unfollow_button.html.erb
<%= button_to 'フォロー解除', relationship_path(current_user.relationships.find_by(follower: user)), class: "follow-button-unfollow", method: :delete, remote: true %>

app/views/relationships/create.js.erb
$("#follow-button").html("<%= j(render 'relationships/unfollow_button', user: @other_user) %>")

app/views/relationships/destroy.js.erb
$("#follow-button").html("<%= j(render 'relationships/follow_button', user: @user) %>")